<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Project.Domain\Project.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="12.0.1" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
		<PackageReference Include="DNTPersianUtils.Core" Version="5.4.4" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Formatters.Json" Version="2.2.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.5" />
		<PackageReference Include="CloudFlare.Client" Version="6.3.0" />
		<PackageReference Include="CloudFlare.NET" Version="0.1.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Serilog" Version="3.1.1" />
	</ItemGroup>
</Project>
